//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Echoglossian.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Echoglossian.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Checking Plugin assets!.
        /// </summary>
        public static string AssetsCheckingPopupMsg {
            get {
                return ResourceManager.GetString("AssetsCheckingPopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Downloading of plugin assets complete!.
        /// </summary>
        public static string AssetsDownloadComplete {
            get {
                return ResourceManager.GetString("AssetsDownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error downloading plugin assets:.
        /// </summary>
        public static string AssetsDownloadError1stPart {
            get {
                return ResourceManager.GetString("AssetsDownloadError1stPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a . Please retry later. If the issue persists, please contact the plugin developer..
        /// </summary>
        public static string AssetsDownloadError2ndPart {
            get {
                return ResourceManager.GetString("AssetsDownloadError2ndPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All plugin assets present!.
        /// </summary>
        public static string AssetsPresentPopupMsg {
            get {
                return ResourceManager.GetString("AssetsPresentPopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ChatGPT API Key.
        /// </summary>
        public static string ChatGptApiKey {
            get {
                return ResourceManager.GetString("ChatGptApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] choice {
            get {
                object obj = ResourceManager.GetObject("choice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close.
        /// </summary>
        public static string CloseButtonLabel {
            get {
                return ResourceManager.GetString("CloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Whats, Whens and Hows.
        /// </summary>
        public static string ConfigTab0Name {
            get {
                return ResourceManager.GetString("ConfigTab0Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Talk settings.
        /// </summary>
        public static string ConfigTab1Name {
            get {
                return ResourceManager.GetString("ConfigTab1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Battle Talk settings.
        /// </summary>
        public static string ConfigTab2Name {
            get {
                return ResourceManager.GetString("ConfigTab2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Toast settings.
        /// </summary>
        public static string ConfigTab3Name {
            get {
                return ResourceManager.GetString("ConfigTab3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Journal settings.
        /// </summary>
        public static string ConfigTab4Name {
            get {
                return ResourceManager.GetString("ConfigTab4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TalkSubtitle settings.
        /// </summary>
        public static string ConfigTab5Name {
            get {
                return ResourceManager.GetString("ConfigTab5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Other settings.
        /// </summary>
        public static string ConfigTab6Name {
            get {
                return ResourceManager.GetString("ConfigTab6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translation Engine settings.
        /// </summary>
        public static string ConfigTab7Name {
            get {
                return ResourceManager.GetString("ConfigTab7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Troubleshooting.
        /// </summary>
        public static string ConfigTab8Name {
            get {
                return ResourceManager.GetString("ConfigTab8Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Automatically copy the last translation to the Plugin Clipboard.
        /// </summary>
        public static string ConfigTab9CheckboxClipboardText {
            get {
                return ResourceManager.GetString("ConfigTab9CheckboxClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This setting copies the last translation and source text to the clipboard (Works with Talk and BattleTalk).
        /// </summary>
        public static string ConfigTab9CheckboxClipboardTooltipText {
            get {
                return ResourceManager.GetString("ConfigTab9CheckboxClipboardTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Misc. Settings.
        /// </summary>
        public static string ConfigTab9Name {
            get {
                return ResourceManager.GetString("ConfigTab9Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Miscellaneous Plugin Options and Settings.
        /// </summary>
        public static string ConfigTab9Text {
            get {
                return ResourceManager.GetString("ConfigTab9Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a About Echoglossian.
        /// </summary>
        public static string ConfigTabAbout {
            get {
                return ResourceManager.GetString("ConfigTabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Echoglossian Configuration.
        /// </summary>
        public static string ConfigWindowTitle {
            get {
                return ResourceManager.GetString("ConfigWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please support us either by contributing to the project development, submitting issues or helping us with a coffee..
        /// </summary>
        public static string ContribText {
            get {
                return ResourceManager.GetString("ContribText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are the plugin assets downloaded?.
        /// </summary>
        public static string CurrentPluginAssetsStatus {
            get {
                return ResourceManager.GetString("CurrentPluginAssetsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] cutscenechoice {
            get {
                object obj = ResourceManager.GetObject("cutscenechoice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use API Key (recommended).
        /// </summary>
        public static string DeepLTransAPIKey {
            get {
                return ResourceManager.GetString("DeepLTransAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add your DeepL API Key.
        /// </summary>
        public static string DeeplTranslatorApiKey {
            get {
                return ResourceManager.GetString("DeeplTranslatorApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Click here to create a DeepL API Key.
        /// </summary>
        public static string DeepLTranslatorAPIKeyLink {
            get {
                return ResourceManager.GetString("DeepLTranslatorAPIKeyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This plugin is aimed at solving one of the biggest issues for audiences that do not speak either English, German, French or Japanese: Understanding dialogues and other elements of the Game UI..
        /// </summary>
        public static string DisclaimerText1 {
            get {
                return ResourceManager.GetString("DisclaimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a For now we only do auto-translations through Google Translate API, but in the future we intend to support other ML translation systems. We even have ideas targetting crowdsourced translations, curated by the community..
        /// </summary>
        public static string DisclaimerText2 {
            get {
                return ResourceManager.GetString("DisclaimerText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a About Echoglossian:.
        /// </summary>
        public static string DisclaimerTitle {
            get {
                return ResourceManager.GetString("DisclaimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Downloading extra plugin assets in background. Please wait for the download to finish before opening settings!.
        /// </summary>
        public static string DownloadingAssetsPopupMsg {
            get {
                return ResourceManager.GetString("DownloadingAssetsPopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Force re-download plugin assets.
        /// </summary>
        public static string DownloadPluginAssetsButtonText {
            get {
                return ResourceManager.GetString("DownloadPluginAssetsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Attention!.
        /// </summary>
        public static string EchoglossianPathModal {
            get {
                return ResourceManager.GetString("EchoglossianPathModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Activate game text realtime translation.
        /// </summary>
        public static string EnableTranslation {
            get {
                return ResourceManager.GetString("EnableTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Overlay font color:.
        /// </summary>
        public static string FontColorSelectLabel {
            get {
                return ResourceManager.GetString("FontColorSelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Opens Echoglossian config window.
        /// </summary>
        public static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (?).
        /// </summary>
        public static string HoverTooltipIndicator {
            get {
                return ResourceManager.GetString("HoverTooltipIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjust the options related to the translation overlay:.
        /// </summary>
        public static string ImguiAdjustmentsLabel {
            get {
                return ResourceManager.GetString("ImguiAdjustmentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The language could not be identified with an acceptable degree of certainty.
        /// </summary>
        public static string LangIdentError {
            get {
                return ResourceManager.GetString("LangIdentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The selected language is not supported by the currently available translation backend.
        /// </summary>
        public static string LanguageNotSupportedText {
            get {
                return ResourceManager.GetString("LanguageNotSupportedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The selected language is only supported using the plugin overlays due to limitations of the native game Font.
        /// </summary>
        public static string LanguageOnlySupportedUsingOverlay {
            get {
                return ResourceManager.GetString("LanguageOnlySupportedUsingOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Which language to translate the in-game dialogue boxes to..
        /// </summary>
        public static string LanguageSelectionTooltip {
            get {
                return ResourceManager.GetString("LanguageSelectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Language to translate to.
        /// </summary>
        public static string LanguageSelectLabelText {
            get {
                return ResourceManager.GetString("LanguageSelectLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] minfilia {
            get {
                object obj = ResourceManager.GetObject("minfilia", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Echoglossian.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The non-exhaustive list of issues and TODOs is available in the link below:.
        /// </summary>
        public static string NEListText {
            get {
                return ResourceManager.GetString("NEListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please adjust position if your overlay is not centered relative to the game&apos;s UI text box..
        /// </summary>
        public static string OverlayAdjustmentOrientations {
            get {
                return ResourceManager.GetString("OverlayAdjustmentOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OverlayColorSelect.
        /// </summary>
        public static string OverlayColorSelectName {
            get {
                return ResourceManager.GetString("OverlayColorSelectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Click to choose the overlay font color.
        /// </summary>
        public static string OverlayFontColorOrientations {
            get {
                return ResourceManager.GetString("OverlayFontColorOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjust the Overlay font scale.
        /// </summary>
        public static string OverlayFontScaleLabel {
            get {
                return ResourceManager.GetString("OverlayFontScaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Overlay Font Size.
        /// </summary>
        public static string OverlayFontSizeLabel {
            get {
                return ResourceManager.GetString("OverlayFontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select the font size for the text overlay.
        /// </summary>
        public static string OverlayFontSizeOrientations {
            get {
                return ResourceManager.GetString("OverlayFontSizeOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translation Overlay Height multiplier.
        /// </summary>
        public static string OverlayHeightScrollLabel {
            get {
                return ResourceManager.GetString("OverlayHeightScrollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Battle talk (Enenies dialogue lines) translation.
        /// </summary>
        public static string OverlayName {
            get {
                return ResourceManager.GetString("OverlayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Position adjustment.
        /// </summary>
        public static string OverlayPositionAdjustmentLabel {
            get {
                return ResourceManager.GetString("OverlayPositionAdjustmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Display translated text overlay above game UI text box instead of replacing its text with the translation.
        /// </summary>
        public static string OverlayToggleLabel {
            get {
                return ResourceManager.GetString("OverlayToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjust translation overlay width.
        /// </summary>
        public static string OverlayWidthMultiplierOrientations {
            get {
                return ResourceManager.GetString("OverlayWidthMultiplierOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translation Overlay Width multiplier.
        /// </summary>
        public static string OverlayWidthScrollLabel {
            get {
                return ResourceManager.GetString("OverlayWidthScrollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Absolute path to Echoglossian folder (inside XIVLauncher -&gt; pluginConfigs folder).
        /// </summary>
        public static string PathInputInstructions {
            get {
                return ResourceManager.GetString("PathInputInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please type the path and save so the plugin can work properly!.
        /// </summary>
        public static string PathTypeInstructions {
            get {
                return ResourceManager.GetString("PathTypeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buy lokinmodar a Coffee.
        /// </summary>
        public static string PatronButtonLabel {
            get {
                return ResourceManager.GetString("PatronButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] pix {
            get {
                object obj = ResourceManager.GetObject("pix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PIX qrcode.
        /// </summary>
        public static string PixQrWindowLabel {
            get {
                return ResourceManager.GetString("PixQrWindowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Scan the QR code to send me a PIX - only valid in Brazil.
        /// </summary>
        public static string PixText {
            get {
                return ResourceManager.GetString("PixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plugin assets downloaded!.
        /// </summary>
        public static string PluginAssetsDownloadedText {
            get {
                return ResourceManager.GetString("PluginAssetsDownloadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a If you see garbled text or invalid characters in the translation window\nit is an indicative that some plugin asset fonts may be missing or corrupted.\n\n Clicking the button below triggers an asset check and re-downloads them..
        /// </summary>
        public static string PluginAssetsNotDownloadedText {
            get {
                return ResourceManager.GetString("PluginAssetsNotDownloadedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose the language for the plugin configuration window.
        /// </summary>
        public static string PluginInterfaceLanguage {
            get {
                return ResourceManager.GetString("PluginInterfaceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Config Window LanguageInfo:.
        /// </summary>
        public static string PluginInterfaceLanguageSelectorText {
            get {
                return ResourceManager.GetString("PluginInterfaceLanguageSelectorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        public static byte[] prttws {
            get {
                object obj = ResourceManager.GetObject("prttws", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Scan the QR code to send me a PIX - only valid in Brazil.
        /// </summary>
        public static string QRCodeInstructionsText {
            get {
                return ResourceManager.GetString("QRCodeInstructionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Reset Settings.
        /// </summary>
        public static string ResetConfigsButton {
            get {
                return ResourceManager.GetString("ResetConfigsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save and Close Config Window.
        /// </summary>
        public static string SaveCloseButtonLabel {
            get {
                return ResourceManager.GetString("SaveCloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send me a PIX donation!.
        /// </summary>
        public static string SendPixButton {
            get {
                return ResourceManager.GetString("SendPixButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Configurations for ChatGPT.
        /// </summary>
        public static string SettingsForChatGptTransText {
            get {
                return ResourceManager.GetString("SettingsForChatGptTransText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Optional settings for DeepL:.
        /// </summary>
        public static string SettingsForDeepLTransText {
            get {
                return ResourceManager.GetString("SettingsForDeepLTransText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Settings for Google Translate:.
        /// </summary>
        public static string SettingsForGTransText {
            get {
                return ResourceManager.GetString("SettingsForGTransText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Echoglossian settings reset to default successfully!.
        /// </summary>
        public static string SettingsReset {
            get {
                return ResourceManager.GetString("SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Show Original dialogue text in Overlay and Translated in the Game UI dialogue box.
        /// </summary>
        public static string SwapTranslationTextToggle {
            get {
                return ResourceManager.GetString("SwapTranslationTextToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adjust toast translation overlay width.
        /// </summary>
        public static string ToastOverlayWidthMultiplierOrientations {
            get {
                return ResourceManager.GetString("ToastOverlayWidthMultiplierOrientations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Toast Overlay Width multiplier.
        /// </summary>
        public static string ToastOverlayWidthScrollLabel {
            get {
                return ResourceManager.GetString("ToastOverlayWidthScrollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TODOs List on Github.
        /// </summary>
        public static string TodoUrl {
            get {
                return ResourceManager.GetString("TodoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate in-game Area name Toast Messages.
        /// </summary>
        public static string TranslateAreaToastToggleText {
            get {
                return ResourceManager.GetString("TranslateAreaToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate battle talk.
        /// </summary>
        public static string TransLateBattletalkToggle {
            get {
                return ResourceManager.GetString("TransLateBattletalkToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate in-game Class/Job change Toast Messages.
        /// </summary>
        public static string TranslateClassChangeToastToggleText {
            get {
                return ResourceManager.GetString("TranslateClassChangeToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate in-game Error Toast Messages.
        /// </summary>
        public static string TranslateErrorToastToggleText {
            get {
                return ResourceManager.GetString("TranslateErrorToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate quest name, description and objectives (WIP).
        /// </summary>
        public static string TranslateJournalToggle {
            get {
                return ResourceManager.GetString("TranslateJournalToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate NPCs names in dialogue boxes.
        /// </summary>
        public static string TranslateNpcNamesToggle {
            get {
                return ResourceManager.GetString("TranslateNpcNamesToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate in-game Quest Toast Messages.
        /// </summary>
        public static string TranslateQuestToastToggleText {
            get {
                return ResourceManager.GetString("TranslateQuestToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate other in-game miscellaneous Toast Messages.
        /// </summary>
        public static string TranslateScreenInfoToastToggleText {
            get {
                return ResourceManager.GetString("TranslateScreenInfoToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate Cutscene Subtitles.
        /// </summary>
        public static string TranslateTalkSubtitleToggleLabel {
            get {
                return ResourceManager.GetString("TranslateTalkSubtitleToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate in-game dialogues.
        /// </summary>
        public static string TranslateTalkToggleLabel {
            get {
                return ResourceManager.GetString("TranslateTalkToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate again stored translated texts with the selected translation engine.
        /// </summary>
        public static string TranslateTextsAgain {
            get {
                return ResourceManager.GetString("TranslateTextsAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translate in-game Toast Messages.
        /// </summary>
        public static string TranslateToastToggleText {
            get {
                return ResourceManager.GetString("TranslateToastToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translations are Disabled!.
        /// </summary>
        public static string TranslationDisabled {
            get {
                return ResourceManager.GetString("TranslationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translations are Enabled!.
        /// </summary>
        public static string TranslationEnabled {
            get {
                return ResourceManager.GetString("TranslationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose the translation engine.
        /// </summary>
        public static string TranslationEngineChoose {
            get {
                return ResourceManager.GetString("TranslationEngineChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This translation engine does not require any special settings..
        /// </summary>
        public static string TranslationEngineSettingsNotRequired {
            get {
                return ResourceManager.GetString("TranslationEngineSettingsNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Translations are Enabled!.
        /// </summary>
        public static string TranslationsEnabled {
            get {
                return ResourceManager.GetString("TranslationsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use overlay to show Toasts translations (WIP).
        /// </summary>
        public static string UseImGuiForToastsToggle {
            get {
                return ResourceManager.GetString("UseImGuiForToastsToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Awaiting translation....
        /// </summary>
        public static string WaitingForTranslation {
            get {
                return ResourceManager.GetString("WaitingForTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select what kind of text you want to be translated in the corresponding tab below!.
        /// </summary>
        public static string WhatToTranslateText {
            get {
                return ResourceManager.GetString("WhatToTranslateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Select which kind of in-game message toasts to translate.
        /// </summary>
        public static string WhichToastsToTranslate {
            get {
                return ResourceManager.GetString("WhichToastsToTranslate", resourceCulture);
            }
        }
    }
}
